In [2]:
import pandas as pd

In [4]:
# 1. csv 파일 읽기
df = pd.read_csv('data/iris.csv')
df

     sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
# 2. DataFrame > csv 파일 저장
df.to_csv('df_to_csv.csv', header = True, index = True, encoding = 'UTF-8')
df = pd.read_csv('df_to_csv.csv')
df

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,sepal length,sepal width,petal length,petal width,target
0,0,0,0,5.1,3.5,1.4,0.2,Iris-setosa
1,1,1,1,4.9,3.0,1.4,0.2,Iris-setosa
2,2,2,2,4.7,3.2,1.3,0.2,Iris-setosa
3,3,3,3,4.6,3.1,1.5,0.2,Iris-setosa
4,4,4,4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...,...,...
145,145,145,145,6.7,3.0,5.2,2.3,Iris-virginica
146,146,146,146,6.3,2.5,5.0,1.9,Iris-virginica
147,147,147,147,6.5,3.0,5.2,2.0,Iris-virginica
148,148,148,148,6.2,3.4,5.4,2.3,Iris-virginica
149,149,149,149,5.9,3.0,5.1,1.8,Iris-virginica

In [16]:
# 3. 데이터 프레임 선언
list = [1,1,1,1]
list
df = pd.DataFrame(list)
type(df)

pandas.core.frame.DataFrame

In [17]:
# 4. 시리즈 선언
list = [1,1,1,1]
se = pd.Series(list)
type(se)

pandas.core.series.Series

In [35]:
# 5. 데이터프레임 요약
df = pd.read_csv('data/iris.csv')
df.info() # 데이터 개수, 컬럼, 타입, Null
print(df['sepal length'].size)
print(df.shape) # 튜플 형태로 행/열 수 반환
print(df['sepal length'].min())
print(df['sepal length'].max())
print(df['target'].unique()) # distinct

print(df['sepal length'].mean()) # NaN 제외
print(df['sepal length'].count()) # NaN 제외
print(df['target'].value_counts()) # NaN 제외

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   target        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
150
(150, 5)
4.3
7.9
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
5.843333333333334
150
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: target, dtype: int64

In [116]:
# 6. 데이터 프레임 인덱스 확인/추가/리셋
df = pd.read_csv('data/iris.csv')
# sepal : 꽃받침, petal : 꽃잎
# drop = True가 기본 > 인덱스로 설정시 컬럼에 남아있지 않냐?(drop = True), 컬럼에 남아있냐(drop = False)
df.set_index('target', inplace = True, drop = False) # 특정 컬럼을 인덱스로 사용, inplace = True : 별도의 대입없이 바로 사용
print(df)
print('----------')
df.set_index('petal length', inplace = True) # petal length로 인덱스를 재지정시, 위의 petal length 인덱스는 자동 삭제
print(df)
print('----------')
df.set_index('petal width', inplace = True) # petal width로 인덱스를 재지정시, 위의 petal length 인덱스는 자동 삭제
print(df)
print('----------')
# drop = False가 기본, 직전 인덱스가 컬럼에 남아있냐(drop = False), 컬럼에 남아있지 않냐?(drop = True)
df.reset_index(inplace = True) # 기본 인덱스로 설정, petal width 인덱스는 컬럼으로 이동(drop = False)
print(df.index)
df

                sepal length  sepal width  petal length  petal width  \
target
Iris-setosa              5.1          3.5           1.4          0.2
Iris-setosa              4.9          3.0           1.4          0.2
Iris-setosa              4.7          3.2           1.3          0.2
Iris-setosa              4.6          3.1           1.5          0.2
Iris-setosa              5.0          3.6           1.4          0.2
...                      ...          ...           ...          ...
Iris-virginica           6.7          3.0           5.2          2.3
Iris-virginica           6.3          2.5           5.0          1.9
Iris-virginica           6.5          3.0           5.2          2.0
Iris-virginica           6.2          3.4           5.4          2.3
Iris-virginica           5.9          3.0           5.1          1.8

                        target
target
Iris-setosa        Iris-setosa
Iris-setosa        Iris-setosa
Iris-setosa        Iris-setosa
Iris-setosa        Iris-setosa
Iris-setosa        Iris-setosa
...                        ...
Iris-virginica  Iris-virginica
Iris-virginica  Iris-virginica
Iris-virginica  Iris-virginica
Iris-virginica  Iris-virginica
Iris-virginica  Iris-virginica

[150 rows x 5 columns]
----------
              sepal length  sepal width  petal width          target
petal length
1.4                    5.1          3.5          0.2     Iris-setosa
1.4                    4.9          3.0          0.2     Iris-setosa
1.3                    4.7          3.2          0.2     Iris-setosa
1.5                    4.6          3.1          0.2     Iris-setosa
1.4                    5.0          3.6          0.2     Iris-setosa
...                    ...          ...          ...             ...
5.2                    6.7          3.0          2.3  Iris-virginica
5.0                    6.3          2.5          1.9  Iris-virginica
5.2                    6.5          3.0          2.0  Iris-virginica
5.4                    6.2          3.4          2.3  Iris-virginica
5.1                    5.9          3.0          1.8  Iris-virginica

[150 rows x 4 columns]
----------
             sepal length  sepal width          target
petal width
0.2                   5.1          3.5     Iris-setosa
0.2                   4.9          3.0     Iris-setosa
0.2                   4.7          3.2     Iris-setosa
0.2                   4.6          3.1     Iris-setosa
0.2                   5.0          3.6     Iris-setosa
...                   ...          ...             ...
2.3                   6.7          3.0  Iris-virginica
1.9                   6.3          2.5  Iris-virginica
2.0                   6.5          3.0  Iris-virginica
2.3                   6.2          3.4  Iris-virginica
1.8                   5.9          3.0  Iris-virginica

[150 rows x 3 columns]
----------
RangeIndex(start=0, stop=150, step=1)

     petal width  sepal length  sepal width          target
0            0.2           5.1          3.5     Iris-setosa
1            0.2           4.9          3.0     Iris-setosa
2            0.2           4.7          3.2     Iris-setosa
3            0.2           4.6          3.1     Iris-setosa
4            0.2           5.0          3.6     Iris-setosa
..           ...           ...          ...             ...
145          2.3           6.7          3.0  Iris-virginica
146          1.9           6.3          2.5  Iris-virginica
147          2.0           6.5          3.0  Iris-virginica
148          2.3           6.2          3.4  Iris-virginica
149          1.8           5.9          3.0  Iris-virginica

[150 rows x 4 columns]

In [57]:
# 7. 데이터 프레임 값 확인
df.values[1:3, 1:2] # 행/열(index 기준)

array([[4.9],
       [4.7]])

In [73]:
# 8. 데이터 프레임 컬럼확인, 컬럼명변경, 컬럼타입변경
df = pd.read_csv('data/iris.csv')
print(df.columns)
df.columns = ['a_a', 'b_b', 'c_c','d_d','e_e']
df.columns = df.columns.str.replace('_','')
df.info()
df['aa'] = df['aa'].astype('int') # str, int, float
df.info()
df = df.convert_dtypes() # 모든 컬럼에 대해 가능한 가장 적절한 dtypes로 변경
df.info()

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'target'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   aa      150 non-null    float64
 1   bb      150 non-null    float64
 2   cc      150 non-null    float64
 3   dd      150 non-null    float64
 4   ee      150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   aa      150 non-null    int64
 1   bb      150 non-null    float64
 2   cc      150 non-null    float64
 3   dd      150 non-null    float64
 4   ee      150 non-null    object
dtypes: float64(3), int64(1), object(1)
memory usage: 6.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   aa      150 non-null    Int64
 1   bb      150 non-null    Float64
 2   cc      150 non-null    Float64
 3   dd      150 non-null    Float64
 4   ee      150 non-null    string
dtypes: Float64(3), Int64(1), string(1)
memory usage: 6.6 KB

In [87]:
# 9. 데이터 프레임 행/열 선택
# loc : 레이블 기반 인덱서, iloc : 위치 기반 인덱서
df = pd.read_csv('data/iris.csv')
print(df)
df_loc = df.loc[1:4,['sepal length' ,'petal width']] # 4행(닫힌구간), 2열
print(df_loc)
# 참고
# 1 < x < 4, (1,4) : 열린구간
# 1 <= x <= 4, [1,4] : 닫힌구간
# 1 <= x < 4 or 1 < x <= 4, [1,4) or (1:4] : 반열린구간(반닫힌구간) > 보통 1 <= x < 4
df_iloc = df.iloc[1:4, [0,3]] # 3행(반열린구간), 2열
print(df_iloc)

     sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
   sepal length  petal width
1           4.9          0.2
2           4.7          0.2
3           4.6          0.2
4           5.0          0.2
   sepal length  petal width
1           4.9          0.2
2           4.7          0.2
3           4.6          0.2

In [103]:
# 10. 데이터 프레임 행 추가/삭제
df = pd.read_csv('data/iris.csv')
list = [[99.0, 98.0, 97.0, 96.0,'sample']] # 행으로 만들기 위해 대괄호 2개
sample = pd.DataFrame(list, columns = df.columns)
print(sample)
print('----------')
df = df.append(sample)
print(df) # append 직후 index 재설정 필요
print('----------')
df.reset_index(drop = True, inplace = True)
print(df) # append 직후 index 재설정 필요
print('----------')
df = pd.concat([df,sample], axis = 0) # pandas에서 append 미추천
df.reset_index(drop = True, inplace = True)
df

   sepal length  sepal width  petal length  petal width  target
0          99.0         98.0          97.0         96.0  sample
----------
     sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica
0            99.0         98.0          97.0         96.0          sample

[151 rows x 5 columns]
----------
     sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica
150          99.0         98.0          97.0         96.0          sample

[151 rows x 5 columns]
----------

/var/folders/6h/rfqq6xd56x342xrf68lt5zw80000gn/T/ipykernel_1305/652212244.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(sample)

     sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica
150          99.0         98.0          97.0         96.0          sample
151          99.0         98.0          97.0         96.0          sample

[152 rows x 5 columns]